### PR TITLE
Compatibility with Samsung and HTC based ROMs

### LINKED ISSUE #7: TouchWiz Support
Please add copy of NotoColorEmoji.ttf in fonts directory under name SamsungColorEmoji.ttf and it will replace ugly Samsung Emojis also on Samsung Roms.
I manualy updated your zip and it works perfectly.
[Emoji_One-v1.3-4Touchwiz.zip](https://github.com/Magisk-Modules-Repo/Magisk-EmojiOne-systemless/files/1180948/Emoji_One-v1.3-4Touchwiz.zip)

### PR DESCRIPTION
**Pull request by Helmasaur**
Samsung and HTC based ROMs uses a different file name for emojis font. (closes #7)

### CODE REVIEW

**Comment by jerbear64** [comment]
This would triple the size of the extracted module, and create unnecessary redundancy. A better idea would be to read the system's build.prop and use it to determine what the TTF file should be named. I can work on that tonight, assuming modules are capable of doing this.

**Comment by Helmasaur** [comment]
The issue is that a custom ROM can change the default file name for the emojis. Also, what if there are several emojis files? I mean, which is the file to pick as the one to replace?

I understand this point (and I didn't even think about it!) but is 60 Mo that much for today's phone? It's like about 10 pictures from a good camera phone. (It's a real question as I have way more space than required.

**Comment by jerbear64** [comment]
That line of thinking doesn't account for users with limited or slow bandwidth, which is my main point of concern.

Assuming it isn't just Samsung and HTC that end up being problematic, following the structure of this pull request would require another copy of the TTF to be made for every individual problematic OEM. Figuring it out using scripting at install time negates this.

Good point on custom ROMs, and I'm not finding a non vendor specific way to detect whether a ROM is AOSP based or stock based, but I think we could take a page out of the V4A module's book and have HTC and Samsung users select which they're using during the install process using the volume keys.

**Comment by Helmasaur** [comment]
I don't have much notion about size for bandwidth.

I realized that the file didn't have the same name seeing other repositories. I decided to pull request those which didn't have the three different files.

Actually, I realize that it would have been good to have a core repository for emojis with forks for each type of emojis. Maybe in the future!

**Comment by Helmasaur** [comment]
This discussion is interesting: https://github.com/Magisk-Modules-Repo/blobmoji/pull/8

**Comment by jerbear64** [comment]
This is now done identically to Blobmoji in ea09325.

**Pull request closed without merging**
